version: '3.1'
services:
  web:
    image: shorturl
    container_name: shorturl
    restart: always
    ports:
      - "8080:80"
    volumes:
      - /home/toaivo/shorturl/data/links.txt:/data/links.txt
      - /home/toaivo/shorturl/roothtml:/usr/local/apache2/htdocs
      - /home/toaivo/shorturl/logs:/usr/local/apache2/logs
      
